<?php

/**
 * @file
 * A module which allows Drupal node data to be saved in a Fedora
 * Repository.
 */

/**
 * Implements hook_entity_info().
 */
function rainhat_entity_info() {

  $return['rainhat_fedora_connection'] = array(
    'label' => t('Fedora Repository Connection'),
    'controller class' => 'RainhatFedoraConnectionController',
    'base table' => 'rainhat_fedora_connection',
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
    ),
  );

  $return['rainhat_node_export'] = array(
    'label' => t('Node Data Export'),
    'controller class' => 'RainhatNodeExportController',
    'base table' => 'rainhat_node_export',
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
    ),
  );
  
  $return['rainhat_datastream'] = array(
    'label' => t('Datastream Definitions'),
    'controller class' => 'RainhatDatastreamController',
    'base table' => 'rainhat_datastream',
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'datastream_id',
    ),
  );
  
  $return['rainhat_node_import'] = array(
    'label' => t('Node Data Import'),
    'controller class' => 'RainhatNodeImportController',
    'base table' => 'rainhat_node_import',
    'fieldable' => FALSE,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
    ),
  );
  
  return $return;
}

/**
 * Implement hook_menu().
 */
function rainhat_menu() {

  $items = array();


  //Fedora Connection Administration ----------------------------------------------------
  $items['admin/config/system/fedora'] = array(
    'title' => 'Fedora Repository Settings',
    'description' => 'Fedora Repository Connections and Node Import/Export Settings',
    'page callback' => 'rainhat_fedoraconnection_list',
    'access arguments' => array('administer fedora connections node export import'),
    'file' => 'rainhat.fedoraconnection.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/system/fedora/connections'] = array(
    'title' => 'Connections',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/system/fedora/fedora/connections/add'] = array(
    'title' => 'Add a Fedora Repository connection',
    'page callback' => 'rainhat_fedora_connection_add',
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'rainhat.fedoraconnection.inc',
  );
  $items['admin/config/system/fedora/connections/%rainhat_fedora_connection/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_fedora_connection_form', 4),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.fedoraconnection.inc',
  );
  $items['admin/config/system/fedora/connections/%rainhat_fedora_connection/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_fedora_connection_delete', 4),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.fedoraconnection.inc',
  );
  $items['admin/config/system/fedora/connections/defaults'] = array(
    'title' => 'Fedora Connection Defaults',
    'access arguments' => array('administer rainhat'),
    'description' => 'Set options for the rainhat module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_admin_form'),
    'file' => 'rainhat.moduleadmin.inc',
    'type' => MENU_CALLBACK,
  );

  //Node Export Administration ----------------------------------------------------------
  $items['admin/config/system/fedora/nodeexport'] = array(
    'title' => 'Node Exports',
    'access arguments' => array('administer fedora connections node export import'),
    'page callback' => 'rainhat_node_export_list',
    'file' => 'rainhat.nodeexport.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/config/system/fedora/nodeexport/add'] = array(
    'title' => 'New Node Export',
    'page callback' => 'rainhat_node_export_add',
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'rainhat.nodeexport.inc',
  );
  $items['admin/config/system/fedora/nodeexport/%rainhat_node_export/edit'] = array(
    'title' => 'Edit a Node Export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_node_export_form', 5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.nodeexport.inc',
  );
  $items['admin/config/system/fedora/nodeexport/%rainhat_node_export/delete'] = array(
    'title' => 'Delete a Node Export',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_node_export_delete', 5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.nodeexport.inc',
  );

  //Datastream Administration -----------------------------------------------------------
  $items['admin/config/system/fedora/datastreams/%rainhat_node_export/add'] = array(
    'title' => 'Add a New Datastream Definition to a Node Export',
    'page callback' => 'rainhat_datastream_add',
    'page arguments' => array(5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.datastream.inc',
  );
  $items['admin/config/system/fedora/datastreams/%rainhat_datastream/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_datastream_form', 5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.datastream.inc',
  );
  $items['admin/config/system/fedora/datastreams/%rainhat_datastream/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_datastream_delete', 5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.datastream.inc',
  );

  //Node Import Administration ----------------------------------------------------------
  $items['admin/config/system/fedora/nodeimport'] = array(
    'title' => 'Node Imports',
    'access arguments' => array('administer fedora connections node export import'),
    'page callback' => 'rainhat_node_import_list',
    'file' => 'rainhat.nodeimport.inc',
    'type' => MENU_LOCAL_TASK,
    'weight' => 1,
  );
  $items['admin/config/system/fedora/nodeimport/add'] = array(
    'title' => 'New Node Import',
    'page callback' => 'rainhat_node_import_add',
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'rainhat.nodeimport.inc',
  );
  $items['admin/config/system/fedora/nodeimport/%rainhat_node_import/edit'] = array(
    'title' => 'Edit a Node Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_node_import_form', 5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.nodeimport.inc',
  );
  $items['admin/config/system/fedora/nodeimport/%rainhat_node_import/delete'] = array(
    'title' => 'Delete a Node Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_node_import_delete', 5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.nodeimport.inc',
  );
  $items['admin/config/system/fedora/nodeimport/%rainhat_node_import/run'] = array(
    'title' => 'Run a Node Import',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('rainhat_node_import_run_form', 5),
    'access arguments' => array('administer fedora connections node export import'),
    'type' => MENU_CALLBACK,
    'file' => 'rainhat.nodeimport.run.inc',
  );

  return $items;

}

/**
 * Implement hook_permission().
 */
function rainhat_permission() {

  $permissions = array();

  $permissions['administer rainhat'] = array(
    'title' => t('Administer the Rainhat module defaults.'),
    'description' => t('Change the Fedora Connection defaults for the Rainhat Module.'),
    'restrict access' => TRUE,
  );

  $permissions['administer fedora connections node export import'] = array(
    'title' => t('Administer Fedora Repository Connections and Node Exports/Imports.'),
    'description' => t('Add, Edit, and Remove connections to Fedora Repositories and the node export settings used to move data to and from Fedora'),
    'restrict access' => TRUE,
  );

  return $permissions;

}

/**
 * Menu load callback for connections.
 */
function rainhat_fedora_connection_load($id) {
  $fedora_connections = entity_load('rainhat_fedora_connection', array($id));
  return reset($fedora_connections);
}

/**
 * Menu load callback for node exports.
 */
function rainhat_node_export_load($id) {
  $node_exports = entity_load('rainhat_node_export', array($id));
  return reset($node_exports);
}

/**
 * Menu load callback for datastreams.
 */
function rainhat_datastream_load($id) {
  $datastreams = entity_load('rainhat_datastream', array($id));
  return reset($datastreams);
}

/**
 * Menu load callback for node imports.
 */
function rainhat_node_import_load($id) {
  $node_imports = entity_load('rainhat_node_import', array($id));
  return reset($node_imports);
}


/**
 * Menu load callback for field imports.
 */
function rainhat_field_import_load($id) {
  $fields = entity_load('rainhat_field_import', array($id));
  return reset($fields);
}

/**
 * Implements hook_node_insert().
 */
function rainhat_node_insert($node){
  rainhat_update_hooked_nodes($node);
}

  
/**
 * Implements hook_node_update().
 */
function rainhat_node_update($node){
  rainhat_update_hooked_nodes($node);
}

function rainhat_update_hooked_nodes($node){

  //Load the node export entities
  $node_export = entity_load('rainhat_node_export');
  foreach ($node_export as $id => $node_export) {
    //Check to see if the node is one of the `hooked` node types
    if ($node->type == $node_export->hooked_type){

      //Get the parent fedora connection data
      $connection = db_select('rainhat_fedora_connection', 'f')
        ->fields('f')
        ->condition('id', $node_export->parent_fedora_connection_id)
        ->execute()
        ->fetchObject();

      //Create the fedora connection
      $fc = new FedoraConnection($connection->url, $connection->admin_username, $connection->admin_password);

      //Check to see if the node has a pid attached to it yet
      $pid = "";

      $nid_to_pid = db_select('rainhat_nid_to_pid', 'rntp')
      ->fields('rntp')
      ->condition('parent_node_export_id', $id)
      ->condition('nid', $node->nid)
      ->execute()
      ->fetchObject();

      if(empty($nid_to_pid)){
        $pid = $fc->ingestNewEmptyObject('new', $node_export->pid_prefix, $node->title)->data;
        $new_row = array('nid'=>$node->nid, 'pid'=>$pid, 'parent_node_export_id'=>$id);
        drupal_write_record('rainhat_nid_to_pid',  $new_row);
        if (user_access('administer fedora connections node export import')) {
          drupal_set_message(t('Nid: @nid is mapped to Pid: @pid.', array('@nid' => $node->nid, '@pid' => $pid)));
        }
      }
      else{
        $pid = $nid_to_pid->pid;
      }
      
      //Update the label
      $fc->updateObject($pid, array('label' => $node->title));

      //Go through the datastreams for the particular transformation, and run them.
      $datastreams = db_select('rainhat_datastream', 'rd')
      ->fields('rd')
      ->condition('parent_node_export_id', $id)
      ->execute();

      foreach ($datastreams as $datastream){
        $new_label = eval('return "'. $datastream->label .'";');
      
        if($datastream->type == 'scripted'){
          $new_datastream = eval($datastream->php_script);
          $fc->addDatastreamData($pid, $datastream->datastream_id, $datastream->control_group, $new_label, $datastream->mime_type, $new_datastream);
        }
       
        else{
          if(empty($datastream->location)){
            //The node object currently in scope is DIFFERENT than the node object returned by node_load.
            //We need the data in the node returned by node_load.
            entity_get_controller('node')->resetCache(array($node->nid));
            $node = node_load($node->nid);
            $field = field_get_items('node', $node, $datastream->file_field, 'und');
            $field = $field[0];
            $fc->addDatastreamData($pid, $datastream->datastream_id, $datastream->control_group, $new_label, $field['filemime'], array($field['filename'] => '@'.drupal_realpath($field['uri']).';type='.$field['filemime']));
          }
          else{
            $new_location = eval('return "'. $datastream->location .'";');
            $fc->addDatastreamLocation($pid, $datastream->datastream_id, $datastream->control_group, $new_label, $datastream->mime_type, $new_location);
          }
        }
      }
    }
  }
}
 
/**
 * Implements hook_node_delete()
 */
function rainhat_node_delete($node){
  
    db_delete('rainhat_nid_to_pid')
      ->condition('nid', $node->nid)
      ->execute();

}

